# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/e/Dev/blocksudoku-solver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/e/Dev/blocksudoku-solver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/e/Dev/blocksudoku-solver/CMakeFiles /mnt/e/Dev/blocksudoku-solver/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/e/Dev/blocksudoku-solver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bssolver

# Build rule for target.
bssolver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bssolver
.PHONY : bssolver

# fast build rule for target.
bssolver/fast:
	$(MAKE) -f CMakeFiles/bssolver.dir/build.make CMakeFiles/bssolver.dir/build
.PHONY : bssolver/fast

#=============================================================================
# Target rules for targets named tests_bssolver

# Build rule for target.
tests_bssolver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests_bssolver
.PHONY : tests_bssolver

# fast build rule for target.
tests_bssolver/fast:
	$(MAKE) -f CMakeFiles/tests_bssolver.dir/build.make CMakeFiles/tests_bssolver.dir/build
.PHONY : tests_bssolver/fast

blockfactory.o: blockfactory.cpp.o

.PHONY : blockfactory.o

# target to build an object file
blockfactory.cpp.o:
	$(MAKE) -f CMakeFiles/bssolver.dir/build.make CMakeFiles/bssolver.dir/blockfactory.cpp.o
	$(MAKE) -f CMakeFiles/tests_bssolver.dir/build.make CMakeFiles/tests_bssolver.dir/blockfactory.cpp.o
.PHONY : blockfactory.cpp.o

blockfactory.i: blockfactory.cpp.i

.PHONY : blockfactory.i

# target to preprocess a source file
blockfactory.cpp.i:
	$(MAKE) -f CMakeFiles/bssolver.dir/build.make CMakeFiles/bssolver.dir/blockfactory.cpp.i
	$(MAKE) -f CMakeFiles/tests_bssolver.dir/build.make CMakeFiles/tests_bssolver.dir/blockfactory.cpp.i
.PHONY : blockfactory.cpp.i

blockfactory.s: blockfactory.cpp.s

.PHONY : blockfactory.s

# target to generate assembly for a file
blockfactory.cpp.s:
	$(MAKE) -f CMakeFiles/bssolver.dir/build.make CMakeFiles/bssolver.dir/blockfactory.cpp.s
	$(MAKE) -f CMakeFiles/tests_bssolver.dir/build.make CMakeFiles/tests_bssolver.dir/blockfactory.cpp.s
.PHONY : blockfactory.cpp.s

blockfactory_tests.o: blockfactory_tests.cpp.o

.PHONY : blockfactory_tests.o

# target to build an object file
blockfactory_tests.cpp.o:
	$(MAKE) -f CMakeFiles/tests_bssolver.dir/build.make CMakeFiles/tests_bssolver.dir/blockfactory_tests.cpp.o
.PHONY : blockfactory_tests.cpp.o

blockfactory_tests.i: blockfactory_tests.cpp.i

.PHONY : blockfactory_tests.i

# target to preprocess a source file
blockfactory_tests.cpp.i:
	$(MAKE) -f CMakeFiles/tests_bssolver.dir/build.make CMakeFiles/tests_bssolver.dir/blockfactory_tests.cpp.i
.PHONY : blockfactory_tests.cpp.i

blockfactory_tests.s: blockfactory_tests.cpp.s

.PHONY : blockfactory_tests.s

# target to generate assembly for a file
blockfactory_tests.cpp.s:
	$(MAKE) -f CMakeFiles/tests_bssolver.dir/build.make CMakeFiles/tests_bssolver.dir/blockfactory_tests.cpp.s
.PHONY : blockfactory_tests.cpp.s

catch.o: catch.cpp.o

.PHONY : catch.o

# target to build an object file
catch.cpp.o:
	$(MAKE) -f CMakeFiles/tests_bssolver.dir/build.make CMakeFiles/tests_bssolver.dir/catch.cpp.o
.PHONY : catch.cpp.o

catch.i: catch.cpp.i

.PHONY : catch.i

# target to preprocess a source file
catch.cpp.i:
	$(MAKE) -f CMakeFiles/tests_bssolver.dir/build.make CMakeFiles/tests_bssolver.dir/catch.cpp.i
.PHONY : catch.cpp.i

catch.s: catch.cpp.s

.PHONY : catch.s

# target to generate assembly for a file
catch.cpp.s:
	$(MAKE) -f CMakeFiles/tests_bssolver.dir/build.make CMakeFiles/tests_bssolver.dir/catch.cpp.s
.PHONY : catch.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/bssolver.dir/build.make CMakeFiles/bssolver.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/bssolver.dir/build.make CMakeFiles/bssolver.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/bssolver.dir/build.make CMakeFiles/bssolver.dir/main.cpp.s
.PHONY : main.cpp.s

main_test.o: main_test.cpp.o

.PHONY : main_test.o

# target to build an object file
main_test.cpp.o:
	$(MAKE) -f CMakeFiles/tests_bssolver.dir/build.make CMakeFiles/tests_bssolver.dir/main_test.cpp.o
.PHONY : main_test.cpp.o

main_test.i: main_test.cpp.i

.PHONY : main_test.i

# target to preprocess a source file
main_test.cpp.i:
	$(MAKE) -f CMakeFiles/tests_bssolver.dir/build.make CMakeFiles/tests_bssolver.dir/main_test.cpp.i
.PHONY : main_test.cpp.i

main_test.s: main_test.cpp.s

.PHONY : main_test.s

# target to generate assembly for a file
main_test.cpp.s:
	$(MAKE) -f CMakeFiles/tests_bssolver.dir/build.make CMakeFiles/tests_bssolver.dir/main_test.cpp.s
.PHONY : main_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... bssolver"
	@echo "... rebuild_cache"
	@echo "... tests_bssolver"
	@echo "... blockfactory.o"
	@echo "... blockfactory.i"
	@echo "... blockfactory.s"
	@echo "... blockfactory_tests.o"
	@echo "... blockfactory_tests.i"
	@echo "... blockfactory_tests.s"
	@echo "... catch.o"
	@echo "... catch.i"
	@echo "... catch.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... main_test.o"
	@echo "... main_test.i"
	@echo "... main_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

